name: publish

on:
  workflow_run:
    workflows: [ build ]
    types:
      - completed
  push:
    branches: [ master ]
  create:
    tags:
      - v*

jobs:
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_os: [ "linux-x64", "win-x64" ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x 
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{runner.os}}-nuget
    - uses: actions/cache@v2
      with:
        path: ./Submodules/SSH.NET/src/Renci.SshNet/bin/Release/netstandard2.0
        key: ssh.net-${{github.sha}}
    - name: Publish
      env:
        TARGET_OS: ${{matrix.target_os}}
        GIT_REF: ${{github.ref_name}}
        GIT_REF_TYPE: ${{github.ref_type}}
        GIT_COMMIT_SHA: ${{github.sha}}
        PROJECT_URL: https://github.com/${{github.repository}}
        REPO_URL: ${{github.repositoryUrl}}
      run: |
        if [ ! -f './Submodules/SSH.NET/src/Renci.SshNet/bin/Release/netstandard2.0/Renci.SshNet.dll' ]; then
          ./build-ssh.net.sh
        fi
        dotnet publish -c SingleFileRelease --self-contained -r $TARGET_OS Wireguard.Cli -o ./out
    - name: Dist
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.target_os}}_prebuild
        path: ./out
